### ISSUE TITLE
eventGenerator.sendPinchCloseWithStartPoint(start, endPoint: end, duration: 0.5) results in crash on iOS 14

### ISSUE THREAD

**Issue by ApplebaumIan** [zalando/SwiftMonkey#97]
When running Monkey Tests on iPadOS 14 targets `eventGenerator.sendPinchCloseWithStartPoint` results in a `Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)`
<img width="1128" alt="Screen Shot 2020-12-20 at 8 44 07 PM" src="https://user-images.githubusercontent.com/9451941/102730916-4450ac80-4304-11eb-9257-4fc8d71950d6.png">

**Comment by ApplebaumIan** [comment]
What's super strange about this bug is that it doesn't appear on the example App...

**Comment by tijme** [comment]
@ApplebaumIan Did you find out what the issue was? I'm currently experiencing the same error.

**Comment by ApplebaumIan** [comment]
@tijme Unfortunately no, I've had to work on other things. I've been just monkey testing my app in iOS 13 for now. 😪

**Comment by ApplebaumIan** [comment]
> @ApplebaumIan Did you find out what the issue was? I'm currently experiencing the same error.

@tijme
Can I ask you a few question since it seems like this is a dead or dying project? Are you using parallel testing, XCTest Plans, or testing an iPad App in landscape?

**Comment by ApplebaumIan** [comment]
@tijme I FINALLY GOT THE EXAMPLE TO BREAK. The issue is that the example is on the latest version of swift monkey on master. So I switched it to using pods and installed version  ` pod 'SwiftMonkeyPaws','~> 2.1.0'` and the example app breaks. 
@zalando please add a new version tag as 2.1.1 is 11 commits behind master.

**Comment by wojciechczerski** [comment]
Thank you very much for finding the cause of this issue! I have drafted a new release (2.2.0). I also left a comment in your PR @ApplebaumIan. After we merge it, I will push the new `Podspec` to CocoaPods.

**Comment by ApplebaumIan** [comment]
@wojciechczerski  Glad to hear it and happy to help! Swift Monkey is a really great tool! Glad I can keep it in my test suite🕺

**Comment by hmttrp** [comment]
👍

**Comment by wojciechczerski** [comment]
@ApplebaumIan @tijme I have pushed SwiftMonkey `2.2.0` to CocoaPods trunk.

**Comment by tijme** [comment]
Thank you for the time and effort you spent on this issue @wojciechczerski & @ApplebaumIan. I am sure you have helped many developers with this fix!

**Comment by manghwanitin** [comment]
I am still facing this issue on Xcode 12 iOS 14.4 even after pointing to 2.2.0. @ApplebaumIan @zalando

**Comment by tijme** [comment]
> I am still facing this issue on Xcode 12 iOS 14.4 even after pointing to 2.2.0. @ApplebaumIan @zalando

Does it work if you replace this `monkey.addDefaultUIAutomationActions()` by `monkey.addDefaultXCTestPublicActions(app: ...)`?

**Comment by manghwanitin** [comment]
That will work. But that is not expected requirements @tijme
